### PR TITLE
Considerations for first technology

### PR DESCRIPTION
**Pull request by wcgeist**
hey guys let me know if you have comments on this, thanks! @adriennefrieden @jchan95 @NStrangio

### CODE REVIEW

**Comment by NStrangio** [comment]
:+1: This looks right to me @wcgeist . I think that's a good overview of the process. I am going to look at those links to dig a little bit deeper for future reference.

**Comment by adriennefrieden** [comment]
Looks good! You might also want to consider adding in PhoneGap as another website to app conversion tool.

**Comment by jchan95** [comment]
:+1: 
Knockin it out the park in the first try. I know a few folks who are in this position and I will forward it onto them.

**Comment by wcgeist** [comment]
@adriennefrieden thanks, I added in the bit about PhoneGap. 
@jchan95 and @NStrangio thanks for pumping my tires, I'll :shipit:

**Comment by adriennefrieden** [comment]
#wcgeist :+1:

**Pull request merged**
